name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2022-07-01
          - nightly-2022-01-01
          - nightly-2021-07-01
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rust-src
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Run tests
        run: cargo test --locked

  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.64.0
          components: rustfmt, clippy
      - name: rustfmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy -- -D warnings
